version: 2.1
commands:
  install-packaged-update-checker:
    description: "install featuretools_update_checker from source distribution"
    steps:
      - run : |
          source test_env/bin/activate
          python setup.py sdist
          FEATURETOOLS_UPDATE_CHECKER_VERSION=$(python setup.py --version)
          tar -zxvf "dist/featuretools_update_checker-${FEATURETOOLS_UPDATE_CHECKER_VERSION}.tar.gz"
          pip install -e "featuretools_update_checker-${FEATURETOOLS_UPDATE_CHECKER_VERSION}/"
          pip install -r "featuretools_update_checker-${FEATURETOOLS_UPDATE_CHECKER_VERSION}/test-requirements.txt"
  run-packaged-tests:
    description: "run unit tests on packaged testing files"
    steps:
      - run: |
          source test_env/bin/activate
          cd "featuretools_update_checker-$(python setup.py --version)/"
          pytest
jobs:
  "python-27":
    working_directory: ~/featuretools_update_checker
    docker:
      - image: circleci/python:2.7-stretch
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-update-checker
      - run: source dev_env/bin/activate && make installdeps
      - run-packaged-tests

  "python-35":
    working_directory: ~/featuretools_update_checker
    docker:
      - image: circleci/python:3.5-stretch
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-update-checker
      - run: source dev_env/bin/activate && make installdeps
      - run-packaged-tests

  "python-36":
    working_directory: ~/featuretools_update_checker
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-update-checker
      - run: source dev_env/bin/activate && make installdeps
      - run: source dev_env/bin/activate && make lint
      - run-packaged-tests

  "python-37":
    working_directory: ~/featuretools_update_checker
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - run: virtualenv test_env && virtualenv dev_env
      - install-packaged-update-checker
      - run: source dev_env/bin/activate && make installdeps
      - run-packaged-tests

workflows:
  version: 2
  test_all_python_versions:
    jobs:
      - "python-27"
      - "python-35"
      - "python-36"
      - "python-37"
